Fix AttributeError: Session obj has no attribute 'sprites'
Previously, the Session class only had an annotation for the sprites attribute, which was'nt initialised anywhere.
Now attribute sprites is initialised as an empty dictionary.